Polychromic Clothing, new loadout reward
WaspStation/WaspStation-1.0 pull request #411
Opened 2020-08-27 16:32 UTC by SynnGraffkin

## About The Pull Request

Ports Polychromic clothing in their current state, made by Ghommie, using [Polychromic element](https://github.com/Citadel-Station-13/Citadel-Station-13/pull/11379) as the primary reference for the current state of what to bring here. 

This adds in a set of clothes that can be earned via Metacoins (or whatever we eventually rename it to) that the colors can be changed on the fly. Jumpsuit slot items are 5k points, the winter coat is 5k points, and the cloak is 10k points (variables can be changed)

A side effect of this, which can probably be atomized into its own PR, is that while moving the Under clothing procs from clothing to _under, I also put in Cit's ability to ctrl click your jumpsuit to immediately max your sensors.

Setting DNM label for now until changing the clothing colors ACTUALLY works and doesn't runtime like hell.

Primarily putting the PR up now, since there was the debate on cloaks being an option at all, and maybe someone smarter knows how to fix color runtimes.

## Changelog
:cl:
add: Polychromic clothing added to the Loadout coin shop in player preferences. Now we can really see who has a sense of color coordination.
add: Jumpsuit slot items that have suit sensors can now be ctrl clicked to immediately max sensors.
/:cl:

2020-08-27 16:54 UTC, tiramisuapimancer commented
Mald signed off on the horny items?

2020-08-27 16:55 UTC, Maldaris commented
> Mald signed off on the horny items?

wait there was more than pantsu?

2020-08-27 16:55 UTC, triplezeta commented
what horny items- wait i see them now

2020-08-27 17:00 UTC, SynnGraffkin commented
I DID show you both the pantsu and the bottomless shirt. ( ͡° ͜ʖ ͡°)

2020-08-27 17:03 UTC, SynnGraffkin commented
Either way, the more horny options can obviously be commented out or at least left in as spawnable objects instead of a loadout item. It's just fun getting initial reactions.

2020-09-03 19:18 UTC, Superyodeler requested changes
I could access the polychrome objects' color change menu, but none of them actually changed color.
Also, the button for changing color was just a picture of the object, with no button background to make it easier to click.

2020-09-03 19:18 UTC, Superyodeler commented on code/datums/action.dm
> +	var/atom/target = null //Wasp - Cit #11379
Did you make sure this won't break anything?

2020-09-03 19:21 UTC, Superyodeler commented
Just noticed the runtime:

[15:09:50] Runtime in ,: bad arg name 'color'
  usr: Guest-767415254/(Timothy Callison)
  usr.loc: (Construction Area (42, 56, 2))

2020-09-03 19:24 UTC, SynnGraffkin commented
```Primarily putting the PR up now, since there was the debate on cloaks being an option at all, and maybe someone smarter knows how to fix color runtimes.```

I haven't touched it in a while, as I was occupied by other things.

2020-09-03 19:41 UTC, Superyodeler commented
Whoops, I should have read the PR more closely.

2020-09-03 19:50 UTC, SynnGraffkin commented
I trust Ghommie as a genius the atom thing shouldn't be an issue, but solving the color argument will be... annoying.

2020-09-08 05:27 UTC, dee-dubya commented
Honestly not too keen on this one, it feels like it'll murder the easy to identify departmental identity of someone at a glance if everyone can just wear a gay pride suit after enough playtime.

On the other hand, people can already swap out their uniforms for silly shit as-is, so it's not that big a deal I suppose.

not gonna say no to it or anything, just not particularly looking forward to it

2020-09-13 03:15 UTC, SynnGraffkin commented
Thanks @untrius for finding the problem with color arguments. Still gotta get winter coat and cloak working proper but progress 👏

2020-09-13 03:16 UTC, SynnGraffkin commented on code/datums/action.dm
> +	var/atom/target = null //Wasp - Cit #11379
Resolved - I was missing the background for the button entirely.

2020-09-13 08:19 UTC, tiramisuapimancer commented
Couple of requests here- Cit recently had a fix PR for things like the winter coat where the hood was allegedly bugged and wouldn't polychrome.

The second thing is that can you please make the background to the polychrome action button not animated. It's so distracting on Cit and I hate it so much

2020-09-13 08:36 UTC, SynnGraffkin commented
Well, the winter coat thing didn't fix them, as we found out in testing.

2020-09-22 04:54 UTC, SynnGraffkin commented
Is not stale, I'm just lazy.

2020-10-07 00:05 UTC, closed without merging