Minor healing chemical nerf.
WaspStation/WaspStation-1.0 pull request #423
Opened 2020-09-03 22:34 UTC by Sparrowbird611

After having a talk with Dream Crusha and TripleZeta, I thought I'd put an idea I had into action. Changes listed here

- Silver Sulfadiazine and Styptic Powder deal 0.6 stamina damage every time they metabolize.
- Synthlflesh deals one stamina damage for every one unit of real damage healed.

These should be minor nerfs to the chemicals, to make them a little less effective mid combat, but still useful.

2020-09-03 22:35 UTC, triplezeta commented
:+1: Good changes

I've said this before but I'd prefer if silver sulf and styptic had proportional stamina damage dealt on splash/touch similar to how synthflesh is here. Otherwise, this is a PR I welcome with open arms. Death to patchchems.

2020-09-03 22:38 UTC, Sparrowbird611 commented
I may look at that idea, but for now I want to see how this works out first before I move on to that.

2020-09-03 22:50 UTC, Superyodeler commented
> carbies
harmies
burnies

I hate this

2020-09-03 22:55 UTC, triplezeta commented
dont worry he does too

2020-09-03 23:04 UTC, Sparrowbird611 commented
Can we all agree we hate this? I'm too lazy to change it though.

2020-09-04 06:17 UTC, tiramisuapimancer commented
based

2020-09-07 03:48 UTC, MarkSuckerberg requested changes

2020-09-07 03:48 UTC, MarkSuckerberg commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +			if(HAS_TRAIT_FROM(M, TRAIT_HUSK, "burn") && carbies.getFireLoss() < THRESHOLD_UNHUSK && (carbies.reagents.get_reagent_amount(/datum/reagent/medicine/C2/instabitaluri) + reac_volume >= 100))
```suggestion
			if(HAS_TRAIT_FROM(M, TRAIT_HUSK, "burn") && carbies.getFireLoss() < THRESHOLD_UNHUSK && (carbies.reagents.get_reagent_amount(/datum/reagent/medicine/synthflesh) + reac_volume >= 100))
```

2020-09-08 20:44 UTC, Superyodeler requested changes
The stamina damage for silver sulf and styptic appears to get removed right after it is applied when there is no other stamina damage. My best guess is that it's not doing enough stamina damage to reset the regen countdown.

Also, please change carbies/harmies/burnies to something less annoying. Using VSCode, you can just select the variable and pick the change all occurrences option in the right click menu.

2020-09-23 00:04 UTC, closed without merging