Shotgun screwery.
WaspStation/WaspStation-1.0 pull request #426
Opened 2020-09-04 02:44 UTC by Sparrowbird611

Title says it all. An overdue shotgun nerf. I really want to rebalance more weapons, but I think I'll start with this. I could go into the details, but basically this PR just massively reduces the damage of all shotgun ammo.

- Slugs deal 30 damage, leading to 4 hits to crit, 2 to slowdown. I know, same number as the stechkin and .45, but one of those is a traitor gun and the other barely exists. The change was necessary to differentiate hits to crit, which in our current state of balance, the slug shotgun crits in the same number of shots as the buckshot does. This makes it so the slug isn't always the superior choice for those with decent aim.

- Buckshot deals 45 damage, leading to 3 hits to kill at close range, one to slowdown. Damage falloff was raised by 0.05, making it 0.8 damage lost per tile. The buckshot shotgun should still be a force to be reckoned with at close range, but making it a little more fair to fight against.

I know, nerfs aren't popular things, but this is long overdue. The only weapon that can even compete with these things in terms of sheer damage is the deagle/traitor revolver, and those things are insanely expensive and rare, while shotguns are, quite literally, laying all over the place (it's hilarious how many shotguns the ship has, and how much damage they dish out). All in all, this should make these more balanced weapons.

2020-09-04 23:43 UTC, Superyodeler requested changes
Needs margularizing

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/ammunition/ballistic/shotgun.dm
> +	pellets = 6
```suggestion
	pellets = 6		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 5.5
```suggestion
	damage = 5.5		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	armour_penetration = 10
```suggestion
	damage = 30		// Wasp Edit - Shotgun Nerf
	armour_penetration = 10		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	stamina = 30
```suggestion
	damage = 1		// Wasp Edit - Shotgun Nerf
	stamina = 30		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	knockdown = 10
```suggestion
	stamina = 40		// Wasp Edit - Shotgun Nerf
	knockdown = 10		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	range = 3
```suggestion
	range = 3		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	damage = 25
```suggestion
	damage = 25		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	var/tile_dropoff_s = 0.8
```suggestion
	var/tile_dropoff = 0.8		// Wasp Edit - Shotgun Nerf
	var/tile_dropoff_s = 0.8		// Wasp Edit - Shotgun Nerf
```

This could also probably be moved to the waspstation folder

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	damage = 7
```suggestion
	damage = 7		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	stamina = 7
```suggestion
	damage = 1		// Wasp Edit - Shotgun Nerf
	stamina = 7		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:43 UTC, Superyodeler commented on code/modules/vending/wardrobes.dm
> +					/obj/item/storage/box/rubbershot = 1,
```suggestion
					/obj/item/storage/box/rubbershot = 1,		// Wasp Edit - Shotgun Nerf
```

2020-09-06 21:59 UTC, dee-dubya commented
this one's definitely the best of the three options, and it saddens me that people are so attached to their shotgun memes that it won't win the vote

2020-09-06 22:00 UTC, triplezeta commented
It's a shame.

Yodeler's PR is going to win out because it's the least extreme of the 3 nerfs; a compromise of sorts.

2020-09-11 01:28 UTC, Maldaris commented
Closing due to voting.

2020-09-11 01:28 UTC, closed without merging