Sane Shotgun Rebalance
WaspStation/WaspStation-1.0 pull request #428
Opened 2020-09-04 17:36 UTC by AsciiSquid

## About The Pull Request
An edit of #426 that keeps non-lethal rounds a bit higher up. Meaning:

- Beanbag slugs go from 55 -> 50 stamina damage.

- Buckshot pellets from 12.5 -> 8, totaling 48 damage point-blank

- Stamina damage falloff goes from 0.5 -> 0.6

All other changes match the original PR

## Why It's Good For The Game
Most of sparrows changes were good, but nerfing non-lethals seems redundant.

## Changelog
:cl:
balance: shotguns are generally worse.
/:cl:

2020-09-04 23:46 UTC, Superyodeler requested changes
Needs margularizing

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 6
```suggestion
	damage = 6		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	armour_penetration = 10
```suggestion
	damage = 30		// Wasp Edit - Shotgun Nerf
	armour_penetration = 10		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	stamina = 50
```suggestion
	stamina = 50		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	knockdown = 10
```suggestion
	stamina = 40		// Wasp Edit - Shotgun Nerf
	knockdown = 10		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	range = 4
```suggestion
	range = 4		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	damage = 25
```suggestion
	damage = 25		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	var/tile_dropoff_s = 0.6
```suggestion
	var/tile_dropoff = 0.8		// Wasp Edit - Shotgun Nerf
	var/tile_dropoff_s = 0.6		// Wasp Edit - Shotgun Nerf
```

Could also probably be put in the waspstation folder

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	damage = 8
```suggestion
	damage = 8		// Wasp Edit - Shotgun Nerf
```

2020-09-04 23:46 UTC, Superyodeler commented on code/modules/projectiles/projectile/bullets/shotgun.dm
> +	stamina = 8
```suggestion
	damage = 1		// Wasp Edit - Shotgun Nerf
	stamina = 8		// Wasp Edit - Shotgun Nerf
```

2020-09-07 03:33 UTC, AsciiSquid commented
Closing because this PR is bad and I am bad for making it

2020-09-07 03:33 UTC, closed without merging