Tweaking the hybrid disabler
WaspStation/WaspStation-1.0 pull request #429
Opened 2020-09-04 18:54 UTC by Sparrowbird611

Another fun PR from yours truly. Swaps out these two aspects of the adv disabler.

The disabler now does 21 stamina damage per shot.

The taser bolt had its range reduced, and deal 30 stamina damage per shot.

Also going to lower the energy resistance of armor.

This should make a more balanced hybrid taser.

2020-09-04 18:56 UTC, triplezeta commented
> 21

i hate you

2020-09-04 20:45 UTC, Sparrowbird611 commented
pushed to wrong branch.

2020-09-22 00:32 UTC, Superyodeler requested changes
Works, even if I don't think the disabler and electrode shots needed to be nerfed that hard.
The main coding issue is that the lack of a newline is making the linter angry.

2020-09-22 00:32 UTC, Superyodeler commented on code/modules/projectiles/projectile/energy/stun.dm
> +	impact_type = /obj/effect/projectile/impact/stun
Needs a newline here.

2020-09-23 14:47 UTC, Sparrowbird611 commented on code/modules/projectiles/projectile/energy/stun.dm
> +	impact_type = /obj/effect/projectile/impact/stun
Should be fixed.

2020-09-23 14:49 UTC, triplezeta commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/vest/russian
make sure you edit the russian surplus crate if you're going to do that

2020-09-23 14:51 UTC, Sparrowbird611 commented
I don't frankly care for the way disablers work right now. They're better than most of the armory items in the majority of situations, excluding the shotgun which trumps everything 24/7. This makes it so they can still down in four shots on their secondary mode, but their primary mode is inline with lasers. They already come with extra ammo, and easier availability so, they're still great guns.

I've also reduced energy armor on most of the common armor pieces to be inline with laser armor. It now takes the same number of shots to disable with a disabler as it does with a laser.

You can say that this will make people swap to using only lethals, but I don't believe that will be the case anymore than it already is.

2020-09-23 15:15 UTC, Sparrowbird611 commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/vest/russian
I just noticed that, thank you for the reminder.

I'll nerf the coat energy protect to be on par with the las protect, but should I buff the russian vest to be on par with a regular vest, or at least slightly below it? It's kind of a meme that this thing has absolutely zero laser and energy protection, given it's already inferior to the coat in terms of limb protection, It probably should at least protect the one part it covers decently, right?

2020-09-23 15:27 UTC, triplezeta commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/vest/russian
yeah someone nerfed it *hard* after discovering that the person who added russian surplus in the first place made the armor rather strong compared to actual armor options

2020-09-23 15:28 UTC, Sparrowbird611 commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/armor/vest/russian
Based cargonian main.

2020-09-26 20:44 UTC, Shadowtail117 requested changes

2020-09-26 20:44 UTC, Shadowtail117 commented on code/modules/clothing/suits/armor.dm
> +	armor = list("melee" = 35, "bullet" = 30, "laser" = 30, "energy" = 30, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)
Missing waspstation disclaimer.

2020-09-26 20:44 UTC, Shadowtail117 commented on code/modules/clothing/suits/armor.dm
> +	armor = list("melee" = 35, "bullet" = 30, "laser" = 30, "energy" = 30, "bomb" = 25, "bio" = 0, "rad" = 0, "fire" = 50, "acid" = 50)
Missing waspstation disclaimer.

2020-09-26 20:44 UTC, Shadowtail117 commented on code/modules/clothing/suits/armor.dm
> +	armor = list("melee" = 25, "bullet" = 20, "laser" = 20, "energy" = 20, "bomb" = 20, "bio" = 50, "rad" = 20, "fire" = -10, "acid" = 50)
Missing waspstation disclaimer.

2020-09-26 20:50 UTC, Sparrowbird611 commented
About all of those, should I put it at the end, or right after the number change?

2020-09-26 21:35 UTC, dinnerwoerror commented on code/modules/projectiles/projectile/energy/stun.dm
> +	range = 3
taser bolt with a range of 3, that's a mild spicy, let's see if this pays off for our intrepid contributor

2020-09-26 21:38 UTC, Sparrowbird611 commented on code/modules/projectiles/projectile/energy/stun.dm
> +	range = 3
2 range was too short IMO, and I felt that this mode should be somewhere between a disabler and a baton. It can be increased later, but 7 felt too long IMO.

2020-09-26 21:39 UTC, dinnerwoerror commented on code/modules/projectiles/projectile/energy/stun.dm
> +	damage = 30
nice catch here son, straight stamina damage at the same level of the old disabler, it wasn't like tasers actually _stunned_ anyone and just made them twitch around for a couple seconds while you missed all of your follow up shots, he's on a bit of a hot streak now

2020-09-26 21:43 UTC, dinnerwoerror commented on code/modules/projectiles/projectile/energy/stun.dm
> +	range = 3
nice, now, how do you think this'll look to the guy running into the center of the AI upload where the taser bolts coming from the turrets will literally be too far away to actually connect

2020-09-26 21:45 UTC, Sparrowbird611 commented on code/modules/projectiles/projectile/energy/stun.dm
> +	range = 3
That one is a good point I have forgotten to take into account. I will increase the range to 5 in this case.

2020-09-26 21:45 UTC, dinnerwoerror commented on code/modules/projectiles/projectile/energy/stun.dm
> +	range = 3
what, did we forget about that? in the code? about how the hybrid turret gun, you know, the AI turrets, how they shoot the same /obj/projectile/energy/electrode as the one we've been nerfing for the past couple months?

2020-09-26 21:47 UTC, dinnerwoerror commented
its neck and neck for sparrow, do you think he can pull through in the vote

2020-09-26 21:48 UTC, Sparrowbird611 commented
Trust me when I say that out of everyone, I'll be the most surprised if I pull this off. I expected everyone to flop on top of me with this one.

2020-09-26 21:55 UTC, dinnerwoerror commented
shrugging off so many taser bolts, any TG player time traveled from 2016 might as well call me Samurai Crack

2020-09-26 22:00 UTC, Sparrowbird611 commented on code/modules/projectiles/projectile/energy/stun.dm
> +	damage = 30
This is false windows. They disable in two shots, as they deal 60 stamina damage. Perhaps your aim is off or the shots are dissipating before contact, because testing reveals I am correct.

2020-09-26 22:15 UTC, Superyodeler commented on code/modules/projectiles/projectile/energy/stun.dm
> +	damage = 30
When you say they disable in two shots, are you referring to current tasers or this taser change?

2020-09-26 22:16 UTC, Sparrowbird611 commented on code/modules/projectiles/projectile/energy/stun.dm
> +	damage = 30
Current tasers disable in two shots. This change reduces them to four. If this was the HoS gun and AI only, I would have found that number to be acceptable, but security was given tasers as standard issue weaponry, so I felt it prudent to nerf them.

2020-09-28 16:40 UTC, Maldaris commented
This doesn't look like it's going to pass the vote. Sorry 😦

2020-09-28 16:40 UTC, closed without merging