Add chatter sound effects from Baystation12
WaspStation/WaspStation-1.0 pull request #434
Opened 2020-09-06 04:35 UTC by Shadowtail117

## About The Pull Request

This PR adds sound effects for when you speak into a radio (excluding hotmiccing) and when you receive a radio transmission. The receiving sound effect is capped at 1-second intervals to avoid overload if you are receiving many messages at once.

These sound effects were ported from Baystation12.

## Why It's Good For The Game

Without these, communication (and the game in general) is very quiet and lacks audible feedback for using your radio like it should.

## Changelog
:cl:
rscadd: Added sound effects for speaking into a radio and receiving a transmission from a radio, ported from Baystation12.
/:cl:

2020-09-06 04:51 UTC, Superyodeler requested changes
Could use some modularizing

2020-09-06 04:51 UTC, Superyodeler commented on code/game/machinery/telecomms/broadcasting.dm
> +
```suggestion
	// Next, we'll have each radio play a small sound effect.			// Wasp Edit begin - Radio chatter
	for(var/obj/item/radio/radio in radios)
		if(radio.last_chatter_time + 1 SECONDS < world.time)
			playsound(radio, "sound/effects/radio_chatter.ogg", 10, FALSE)
			radio.last_chatter_time = world.time			// Wasp Edit end

```

2020-09-06 04:51 UTC, Superyodeler commented on code/game/objects/items/devices/radio/radio.dm
> +	var/last_chatter_time //The time since we last played a radio chatter sound.
```suggestion
	var/last_chatter_time //The time since we last played a radio chatter sound.			// Wasp Edit - Radio chatter
```

2020-09-06 04:51 UTC, Superyodeler commented on code/game/objects/items/devices/radio/radio.dm
> +	playsound(src, "sound/effects/walkietalkie.ogg", 20, FALSE)
```suggestion
	//At this point the signal was transmitted so play a sound			// Wasp Edit - Radio chatter
	playsound(src, "sound/effects/walkietalkie.ogg", 20, FALSE)			// Wasp Edit - Radio chatter
```

2020-09-06 04:56 UTC, Shadowtail117 commented
Thanks for catching that. I haven't had to work with an upstream in a while.

2020-09-06 07:50 UTC, triplezeta commented
oh based

2020-09-07 02:02 UTC, Superyodeler requested changes
It works, but the radio chatter sound is quiet enough that it's hard to hear over the ambient sound.

2020-09-07 02:02 UTC, Superyodeler commented on code/game/machinery/telecomms/broadcasting.dm
> +			playsound(radio, "sound/effects/radio_chatter.ogg", 10, FALSE)
Can you raise the volume (the 10) on this some? Between the low volume and the .ogg being quiet I thought this wasn't working at first.

2020-09-07 02:13 UTC, Shadowtail117 commented on code/game/machinery/telecomms/broadcasting.dm
> +			playsound(radio, "sound/effects/radio_chatter.ogg", 10, FALSE)
Addressed.

2020-09-07 02:38 UTC, Superyodeler approved these changes

2020-09-07 04:02 UTC, MarkSuckerberg approved these changes
Now this is the kinda stuff I like seeing

2020-09-07 04:05 UTC, merged