Skateboards can take you to the afterlife
WaspStation/WaspStation-1.0 pull request #446
Opened 2020-09-09 00:48 UTC by Tallvisit

## About The Pull Request

Makes it so when you use the Suicide command with any of the skateboards in hand, you attempt the forbidden double kickflip and die.

## Why It's Good For The Game

Adds a way for people to kill themselves while making it look like they are still Rad.

## Changelog
:cl:
add: Added suicide text to all Skateboards
/:cl:

2020-09-09 00:54 UTC, Superyodeler requested changes
Looks good, just needs some margularization comments

2020-09-09 00:54 UTC, Superyodeler commented on code/game/objects/items/weaponry.dm
> +	return BRUTELOSS
```suggestion
/obj/item/melee/skateboard/suicide_act(mob/living/carbon/user)			// Wasp Edit Begin - Skateboard to the afterlife
	user.visible_message("<span class='suicide'>[user] begins attempting to preform a double kickflip! It looks like [user.p_theyre()] trying to commit suicide!</span>")
	return BRUTELOSS			// Wasp Edit End
```

2020-09-09 01:11 UTC, Superyodeler approved these changes
Looks good!

2020-09-09 01:12 UTC, Tallvisit commented
Sick, time for victory Mac and Cheese...




Marg and Cheese...

2020-09-09 23:22 UTC, Tallvisit commented
Right, this should be ready to hit the shelves, unless I missed something, I made that harder then it should have been...

Noted changes is just developer notes, an added moodlet, and a chance for the skateboard suicide to trigger this moodlet for onlookers.

2020-09-13 00:28 UTC, MarkSuckerberg approved these changes

2020-09-13 00:30 UTC, merged

2020-09-13 23:35 UTC, Tallvisit commented
Merged! Now everyone can suicide round start for a chance at that gamer mood boost for everyone else.

2020-09-13 23:35 UTC, ADepressedPyroshark commented
> 
> 
> Merged! Now everyone can suicide round start for a chance at that gamer mood boost for everyone else.

brb setting up suicide macro to automate the process