Sleeper rework(?)
WaspStation/WaspStation-1.0 pull request #471
Opened 2020-09-23 03:39 UTC by MarkSuckerberg

## About The Pull Request
![image](https://user-images.githubusercontent.com/29362068/93963919-fa1b5780-fd23-11ea-9bda-00b176385994.png)
*Default sleeper with roundstart chems list, subject to change*

Makes sleepers draw from an attached chembag full of beakers for their reagents, finally eliminating the infinitly spawning medicines and bad band-aids such as power cells.

## Why It's Good For The Game
Makes sleepers no more powerful than any other way of applying medicine, more or less becoming a stationary hypospray with a large amount of reagents.

## Changelog
:cl:
add: Sleepers now draw reagents from an attached chembag
del: Sleepers no longer create infinite medicines out of thin air
del: Removed the party pod. Not going to explain why other than <i>why was it in in the first place</i>
/:cl:

2020-09-23 03:45 UTC, ADepressedPyroshark commented
Can you put in poisons? if no, can that be an emag feature?

2020-09-23 03:46 UTC, ADepressedPyroshark commented
Also, @MarkSuckerberg how will this affect pod sleepers, the mining ones?

2020-09-23 04:02 UTC, MarkSuckerberg commented
![image](https://user-images.githubusercontent.com/29362068/93965410-b32f6100-fd27-11ea-8425-f91434033705.png)

2020-09-23 04:03 UTC, MarkSuckerberg commented
also the mining sleepers will have the same starting chems as the normal one, also subject to change

2020-09-28 00:03 UTC, triplezeta commented on waspstation/code/modules/reagents/reagent_containers/bottle.dm
> +	name = "bicaridine bottle"
bruh

2020-09-28 00:04 UTC, triplezeta requested changes

2020-09-28 00:04 UTC, triplezeta commented on waspstation/code/modules/reagents/reagent_containers/bottle.dm
> +	name = "bicaridine bottle"
bicaridine bottle

2020-09-28 00:27 UTC, triplezeta requested changes

2020-09-28 00:27 UTC, triplezeta commented on waspstation/code/game/machinery/Sleeper.dm
> +	var/list/starting_beakers = list(
missing dexalin in your list

2020-09-29 04:11 UTC, Superyodeler commented on waspstation/code/game/machinery/Sleeper.dm
> -		available_chems |= possible_chems[i]
Does a better manipulator still have an effect with this change?

2020-09-30 01:39 UTC, MarkSuckerberg commented on waspstation/code/game/machinery/Sleeper.dm
> -		available_chems |= possible_chems[i]
Yes, it increases the amount of possible granularities for dispensing chems

2020-09-30 02:08 UTC, Superyodeler commented on waspstation/code/game/machinery/Sleeper.dm
> -		available_chems |= possible_chems[i]
Matter bins affect granularity, not manipulators. It doesn't look like `I` is used for anything now that available_chems aren't a thing.

2020-11-01 06:59 UTC, Superyodeler requested changes
Found one funny bug involving a sleeper being crammed into a beaker.

2020-11-01 06:59 UTC, Superyodeler commented on waspstation/code/game/machinery/Sleeper.dm
> +		forceMove(W, chembag)
This actually puts the sleeper in the beaker, you probably should use the transferItemToLoc proc.

2020-11-11 19:28 UTC, Superyodeler commented
Didn't realize this had been updated, I'll test this out again.

2020-11-12 23:19 UTC, Superyodeler requested changes
The beaker is added to the chembag correctly, but it doesn't appear on the interface until update_contents gets called.

2020-11-12 23:19 UTC, Superyodeler commented on waspstation/code/game/machinery/Sleeper.dm
> +		to_chat(user, "<span class='notice'>You put [W] into [src]'s [chembag].</span>")
```suggestion
		to_chat(user, "<span class='notice'>You put [W] into [src]'s [chembag].</span>")
		update_contents()
```

2020-11-25 00:24 UTC, Superyodeler approved these changes

2020-11-25 07:01 UTC, merged