Nya!~, but it's a punishment from an angry god.
WaspStation/WaspStation-1.0 pull request #475
Opened 2020-09-25 02:01 UTC by MaltVinegar

## About The Pull Request

It makes the a cat tongue an admin punishment.

## Why It's Good For The Game

Nya!~

## Changelog
:cl:
add: adds the cat tongue and associated admin punishment
/:cl:

2020-09-25 02:03 UTC, triplezeta commented
le tongue

2020-09-25 02:05 UTC, ADepressedPyroshark commented
I want to see the effects of this uwu

2020-09-25 02:05 UTC, MaltVinegar commented
I sure hope I didn't fuck something up unknowingly

2020-09-25 02:17 UTC, Shadowtail117 requested changes

2020-09-25 02:17 UTC, Shadowtail117 commented on code/modules/surgery/organs/tongue.dm
> +	var/static/regex/felinid_nyA = new("(n)(\[AEIOU])", "g")//
Can be simplified to:
```suggestion
	var/static/regex/felinid_nya = new("(\[Nn])(\[aeiou])|(\[n])(\[AEIOU])", "g")//Thanks to Shadowtail117
	var/static/regex/felinid_NYA = new("(N)(\[AEIOU])", "g")//
```
This combines all regexes that would result in a lowercase "y" being substituted. See https://regex101.com/r/LlYyko/1.

2020-09-25 02:17 UTC, Shadowtail117 commented on code/modules/surgery/organs/tongue.dm
> +	var/static/regex/felinid_R2W = new("R", "g")
Can be simplified to:
```suggestion
	var/static/regex/felinid_lr2w = new("([lr])", "g")
	var/static/regex/felinid_LR2W = new("([LR])", "g")
```

2020-09-25 02:17 UTC, Shadowtail117 commented on code/modules/surgery/organs/tongue.dm
> +		message = felinid_R2W.Replace(message, "W")
See above comment on lines 336-339.

```suggestion
		message = felinid_lr2w.Replace(message, "w")
		message = felinid_LR2W.Replace(message, "W")
```

2020-09-25 02:17 UTC, Shadowtail117 commented on code/modules/surgery/organs/tongue.dm
> +		message = felinid_nyA.Replace(message, "$1y$2")//
See above comment on lines 340-343.
```suggestion
		message = felinid_nya.Replace(message, "$1$3y$2$4")//Thanks to Shadowtail117
		message = felinid_NYA.Replace(message, "$1Y$2")//
```

2020-09-25 02:24 UTC, MaltVinegar commented on code/modules/surgery/organs/tongue.dm
> +		message = felinid_nyA.Replace(message, "$1y$2")//
Smol coder brain moment

2020-09-25 02:36 UTC, Shadowtail117 commented on code/modules/surgery/organs/tongue.dm
> +	var/static/regex/felinid_LR2W = new("([LR])", "g")
Oops.
```suggestion
	var/static/regex/felinid_lr2w = new("(\[lr])", "g")
	var/static/regex/felinid_LR2W = new("(\[LR])", "g")
```

2020-09-25 02:39 UTC, Shadowtail117 requested changes

2020-09-25 02:39 UTC, Shadowtail117 commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
Should add a Boomerstation disclaimer for this line.

2020-09-25 02:41 UTC, MaltVinegar commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
Let me add that real quick

2020-09-25 03:02 UTC, Superyodeler commented
aeiou

2020-09-25 03:03 UTC, MaltVinegar commented
![image](https://user-images.githubusercontent.com/69946338/94221910-0802e100-feba-11ea-994e-7c3127180d83.png)
![image](https://user-images.githubusercontent.com/69946338/94221922-105b1c00-feba-11ea-996f-1991bcdb9984.png)

2020-09-25 03:08 UTC, Shadowtail117 approved these changes

2020-09-26 04:47 UTC, Maldaris requested changes
So there's some coder QoL stuff that needs to happen here before this gets merged regardless of its functionality. Please make sure you get this done.

2020-09-26 04:47 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
The modularization comment template for this kind of thing is usually `//WaspStation Edit - <PR Name/Feature Name here>`. Make sure you use the same comment regardless for whatever change is made.

2020-09-26 04:47 UTC, Maldaris commented on code/__DEFINES/admin.dm
> +#define ADMIN_PUNISHMENT_NYA "Neko"//Tiny Boomer code by MaltVineger
Same thing here: `//WaspStation Edit - <PR Name/Feature Name here>`.

2020-09-26 04:47 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +		if(ADMIN_PUNISHMENT_NYA)//Boomer code by MaltVineger
For block text like this, you would start with `//WaspStation Start - <PR Name/Feature Name here>`

2020-09-26 04:47 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +			tonje.Insert(dude, TRUE, FALSE)//end of Boomer code, thanks to BAMPOT for helping with this one
and `//WaspStation End - <PR Name/Feature Name here>` at the end.

2020-09-26 04:47 UTC, Maldaris commented on code/modules/surgery/organs/tongue.dm
> +/obj/item/organ/tongue/felinid//Boomer code, taken from this PR 'https://github.com/tgstation/tgstation/pull/53587', modified, and put here by MaltVineger
Same bit here as your other block of changes. However since these are standalone changes, I would recommend putting them in the modular waspstation folder that matches the path for this file, ie `waspstation/code/modules/surgery/organs/tongue.dm`

2020-09-26 04:59 UTC, MaltVinegar commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
Would it be '//WaspStation Edit - <Nya!~, but it's a punishment from an angry god. #475>'?

2020-09-26 05:04 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
You can drop the <> and I'd rather in this case since it's a hahafunnymeme PR name, just do a terse description of the feature, something like: "admin button cat tongue" etc.

2020-09-26 05:07 UTC, MaltVinegar commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
So like '//WaspStation Edit - gives target 'cat tongue''?

2020-09-26 05:08 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +	var/list/punishment_list = list(ADMIN_PUNISHMENT_BREAK_BONES, ADMIN_PUNISHMENT_LIGHTNING, ADMIN_PUNISHMENT_BRAINDAMAGE, ADMIN_PUNISHMENT_GIB, ADMIN_PUNISHMENT_BSA, ADMIN_PUNISHMENT_FIREBALL, ADMIN_P
`//WaspStation Edit - Admin Punishment: Cat Tongue` would be probably the best.

2020-09-27 03:23 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +			tonje.Insert(dude, TRUE, FALSE)//WaspStation End - Admin Punishment: Cat Tongue
Does this remove the existing tongue? (@MarkSuckerberg ?)

2020-09-27 03:29 UTC, Shadowtail117 commented on code/modules/admin/verbs/randomverbs.dm
> +			tonje.Insert(dude, TRUE, FALSE)//WaspStation End - Admin Punishment: Cat Tongue
```
/obj/item/organ/proc/Insert(mob/living/carbon/M, special = 0, drop_if_replaced = TRUE)
	if(!iscarbon(M) || owner == M)
		return

	var/obj/item/organ/replaced = M.getorganslot(slot)
	if(replaced)
		replaced.Remove(M, special = 1)
		if(drop_if_replaced)
			replaced.forceMove(get_turf(M))
		else
			qdel(replaced)
...
```
Yes.

2020-09-27 03:30 UTC, Maldaris commented on code/modules/admin/verbs/randomverbs.dm
> +			tonje.Insert(dude, TRUE, FALSE)//WaspStation End - Admin Punishment: Cat Tongue
👍

2020-09-27 03:31 UTC, Maldaris commented
This should probably be test merged and tested before we call this done, but otherwise it looks good. Vote passed as well.

2020-09-30 01:37 UTC, MarkSuckerberg approved these changes
Looks good, and has been testmerged successfully for a while

2020-09-30 02:11 UTC, dee-dubya commented
<img src="https://cdn.discordapp.com/attachments/221734126070267906/760685274958659604/hqdefault.png">

2020-09-30 02:12 UTC, Superyodeler commented
Buy Skyrim

2020-09-30 02:20 UTC, Maldaris approved these changes

2020-09-30 02:21 UTC, merged