Make e-cigarettes require lighting and add e-cigars
WaspStation/WaspStation-1.0 pull request #479
Opened 2020-09-26 22:42 UTC by Shadowtail117

## About The Pull Request

This PR adds new functionality for e-cigarettes, requiring that they must be lit by a PDA before they will do anything. They can also be "extinguished" in the same way. This also means that they will continue to work even when not in someone's mouth (for the purposes of vape clouds, consuming reagents, etc.)

In addition, a new e-cigar has been added and is available via the contraband inventory of cigarette machines.

**These changes were made on behalf of Lakue.**

## Why It's Good For The Game

This adds an interesting mechanic to vapes that I feel makes them more unique. And what isn't there to love about an e-cigar?

## Changelog
:cl: Shadowtail117 & Lakue
add: Added a new E-cigar, available in the contraband inventory of cigarette vendors.
tweak: E-cigarettes (and the new E-cigar) now need to be lit by using your PDA on them first. You can extinguish them in the same method.
/:cl:

2020-09-27 03:48 UTC, Lakue-Bit commented
Redoing the holographic smoke on the E-Cigar

2020-09-27 04:58 UTC, Lakue-Bit commented
Resprite of the holographic smoke is done. Credit to Azlan for helping me.

2020-09-27 20:03 UTC, Shadowtail117 commented
Sprites have been updated. Ready for review.

2020-09-28 15:48 UTC, Maldaris requested changes

2020-09-28 15:48 UTC, Maldaris commented on code/game/objects/items/cigs_lighters.dm
> +			to_chat(user, "<span class='notice'>You start puffing on \the [src].</span>")
You dropped a call to `START_PROCESSING(SSobj, src)` here, was that intentional?

2020-09-28 15:48 UTC, Maldaris commented on code/game/objects/items/cigs_lighters.dm
> +	else if (slot == ITEM_SLOT_MASK)
This might be less confusing if you used the following branching logic:
```
if(slot == ITEM_SLOT_MASK)
  if(on)
    if(!screw)
      ...screw message
    else
      ...activate message
  else
    ...turn on message
```
At the moment you're doing a weird double-check on `slot == ITEM_SLOT_MASK`

2020-09-28 15:48 UTC, Maldaris commented on code/game/objects/items/cigs_lighters.dm
> +/obj/item/clothing/mask/vape //Begin Waspstation edit - Lightable e-cigarettes
Hate to be a dick about this: Modularizing this is gonna require comments on the specific changes across the file, not just at the top. Maintainers need to know line-for-line which stuff to keep if upstream/ports touch the same file/lines.

2020-09-28 15:50 UTC, Maldaris commented on code/game/objects/items/cigs_lighters.dm
> -		STOP_PROCESSING(SSobj, src)
Same thing here; We need to make sure the vape stops being processed as part of the objects subsystem whenever not in use. With the way this is written, I could print/buy a bunch of vapes, and _theoretically_ cause lag by just turning them on and leaving them on the ground. It's fine to have them in a lit/on state on the ground without processing anything associated with them.

2020-09-28 18:47 UTC, Shadowtail117 commented on code/game/objects/items/cigs_lighters.dm
> -		STOP_PROCESSING(SSobj, src)
It needs to keep processing even when dropped, etc. so that the vape clouds can appear without needing it to be in someone's mouth. I don't smoke or vape IRL so I don't claim to know that much about how it should work, so if this is something that needs reverting let me know.

2020-09-28 18:48 UTC, Shadowtail117 commented on code/game/objects/items/cigs_lighters.dm
> +			to_chat(user, "<span class='notice'>You start puffing on \the [src].</span>")
See comment about the other processing macro. 

The `START_PROCESSING` and `STOP_PROCESSING` calls were moved to when you light/extinguish it using a PDA.

2020-09-28 18:49 UTC, SynnGraffkin commented on code/game/objects/items/cigs_lighters.dm
> -		STOP_PROCESSING(SSobj, src)
Don't the clouds come from explicitly inhaling and then exhaling? They don't come out passively from the device.

2020-09-28 18:51 UTC, Maldaris commented on code/game/objects/items/cigs_lighters.dm
> -		STOP_PROCESSING(SSobj, src)
This. You actually draw the vape "juice" over the aerosolizer heating coils the same way you would pull on a cigarette, which _vaporizes_ the juice producing the vapor cloud.

2020-09-28 18:57 UTC, Maldaris commented on code/game/objects/items/cigs_lighters.dm
> -		STOP_PROCESSING(SSobj, src)
As far as code is concerned, the original comment applies: you can allow the sprite to retain its "on" state with the vapor cloud animation playing as an overlay, but not run any actual processing.

2020-09-28 19:01 UTC, Shadowtail117 commented on code/game/objects/items/cigs_lighters.dm
> +/obj/item/clothing/mask/vape //Begin Waspstation edit - Lightable e-cigarettes
Done.

2020-09-28 19:01 UTC, Shadowtail117 commented on code/game/objects/items/cigs_lighters.dm
> +	else if (slot == ITEM_SLOT_MASK)
Done.

2020-09-28 19:39 UTC, Maldaris approved these changes
This needs to be test merged, and I will add the appropriate tag for that, but otherwise this looks great. Props to you and Lakue.

2020-09-29 04:52 UTC, Lakue-Bit commented
Turning on the E-Cigar and putting it in the mask slot doesn't show the animated sprite that's supposed to be associated to it

2020-09-29 05:50 UTC, Shadowtail117 commented
DNM for now while I fix the above issue.

2020-09-29 06:00 UTC, Shadowtail117 commented
Issue fixed, ready for review.

2020-09-30 05:34 UTC, Lakue-Bit commented
Smaller priority issue, the E-cigar and E-Cig do not change sprites when turned on or off in the mask slot

2020-09-30 06:04 UTC, Shadowtail117 commented
Yeah, I saw that a couple times. Unsure of how to fix it, I make a call to update the icon state whenever it is lit/unlit:

https://github.com/WaspStation/WaspStation-1.0/blob/2496218fbb178298282c2d41aa391d58693315dd/code/game/objects/items/cigs_lighters.dm#L881-L894

My best guess is it's an icon state vs. item state issue.

2020-09-30 15:53 UTC, Shadowtail117 commented
Fixed, the sprite will now update in the mask slot. Price has also been adjusted to 300 credits.

2020-09-30 17:11 UTC, ADepressedPyroshark commented
I'd prefer if this didn't affect the vape tbh

2020-10-02 03:51 UTC, MarkSuckerberg commented on code/game/objects/items/cigs_lighters.dm
> +			to_chat(user, "span class='warning'>You need to turn \the [src] off first!</span>")
```suggestion
			to_chat(user, "<span class='warning'>You need to turn \the [src] off first!</span>")
```
After this, you're clear for merge

2020-10-02 03:58 UTC, merged