Fixes Paper in faxes and on doors
WaspStation/WaspStation-1.0 pull request #484
Opened 2020-09-27 05:38 UTC by MarkSuckerberg

## About The Pull Request
Title.

Ports:
tgstation/tgstation#52470
tgstation/tgstation#53121
tgstation/tgstation#53199

as well as a bit of custom code for faxes

## Why It's Good For The Game
Paper broke, bls fix

## Changelog
:cl:
fix: Papers attached to doors are now readable.
fix: Papers sent to centcom are now readable by admins again.
fix: Stamps work again. Probably.
admin: Secret documents that are faxed to centcom are now "readable."
/:cl:

2020-09-28 04:19 UTC, Maldaris requested changes

2020-10-05 23:57 UTC, Maldaris approved these changes

2020-10-05 23:57 UTC, Maldaris commented on code/modules/paperwork/paper.dm
> +	if(!in_range(user, src) && !isobserver(user))
On a second review; I'll make a feature request to replicate this functionality.

2020-10-05 23:57 UTC, Maldaris commented on code/modules/paperwork/paper.dm
> -	if(!..())
This is apparently elsewhere. Nevermind.

2020-11-05 16:14 UTC, MarkSuckerberg commented
https://youtu.be/VI6dsMeABpU

2020-11-05 16:17 UTC, merged