Really Robust Tape
WaspStation/WaspStation-1.0 pull request #490
Opened 2020-09-30 04:33 UTC by AsciiSquid

## About The Pull Request
Adds new tape objects. Complete with the following features:
+ Can be used as a cheap bandage to stop bleeding, or do minor brute repairs to artificial limbs
+ Using tape on someone with disarm intent will wrap them in tapecuffs, which are quick to deploy and remove (only 20 seconds to break out!)
+ If the mouth is selected with disarm intent, quickly slap a tape muzzle onto someone's face.
+ Coat small, throwable items in tape to give them a harmless embed effect
+ Coat a pair of fingerless gloves to make improvised gripper gloves
But that's not all, there is also **tape variants**!
### Industrial Tapes
This includes the duct tape and electrical tape
These tapes can do all of the above and also can be used to repair **any** item with an obj_integrity.
![taped](https://user-images.githubusercontent.com/39249137/94642958-509c0f00-02ab-11eb-8e17-192d82cb6092.png)
Note that any sharp item or a pair of wirecutters will remove the tape, and any repairs the tape may have been doing.

Electrical tape will also apply insulation to any item it's wrapped in. You can even apply it to gloves for a pair of makeshift insuls! (Warning, this is stupid and has a 50% of not working)

NOTE: This PR does not add a way to make this tape obtainable currently.

## Why It's Good For The Game
This codebase is basically running on duct tape and sorcery, might as well let the players have some.

## Changelog
:cl:
add: Added really robust tape
soundadd: adds tape sounds
imageadd: adds tape pictures
/:cl:

2020-09-30 04:35 UTC, Maldaris commented
You could add this to the You Tool vending machine

2020-09-30 04:35 UTC, tiramisuapimancer commented
algo maintloot or engienering lockers

2020-09-30 04:36 UTC, triplezeta commented
ascii, for the life of me, please don't use hard black for your electrical tape's outlines

2020-09-30 04:36 UTC, triplezeta commented
also good PR, 10/10

2020-09-30 04:37 UTC, ADepressedPyroshark commented
> Electrical tape will also apply insulation to any item it's wrapped in. You can even apply it to gloves for a pair of makeshift insuls! (Warning, this is stupid and has a 50% of not working)

what if I add this to budget insuls?

2020-09-30 13:30 UTC, Sparrowbird611 commented
I like this PR. One thing though, you should probably remove the other method of making gripper gloves if this new one is to be the intended method. The recipe can be found in the crafting folder.

2020-10-03 01:57 UTC, Superyodeler requested changes
Taped on insulated gloves don't appear on players and are impossible to take off. Also, they work 100% of the time, they only take damage 50% of the time.
The tape overlay on taped up machines only appears for me after reloading the game.
Also, the machines repaired with professional-grade duct tape as their tape_used, and not the other kinds of tape, seem to "forget" what tape was used for them after a few minutes, and start reporting runtimes with null values for their tape_used components. I don't know why they do this.

2020-10-03 01:57 UTC, Superyodeler commented on waspstation/code/modules/clothing/gloves/tapegloves.dm
> +		qdel(src)
Gloves are still able to absorb shocks at 0 shocks remaining, they disappear at -1.
```suggestion
	if(shocks_remaining <= 0)
		qdel(src)
```

2020-10-03 01:57 UTC, Superyodeler commented on waspstation/code/game/objects/items/stacks/tape.dm
> +		to_chat(user, "<span class='notice'>[I] looks fine enough to me.</span>")
This should probably be moved up for organization purposes. Not really a big deal.

2020-10-03 02:04 UTC, Superyodeler commented
Also see #504.

2020-10-07 21:32 UTC, AsciiSquid commented
Fixed some of the issues mentioned in comments and #504. Also added duct tape to engineering lockers and packaging tape to the quartermaster locker.

2020-10-11 21:25 UTC, Superyodeler requested changes
Finally figured out what was causing those runtimes, InheritComponent was being passed an null taped component and was causing runtimes when it tried to pull a tape_used out of it.

2020-10-11 21:25 UTC, Superyodeler commented on waspstation/code/datums/components/taped.dm
> +	src.tape_used = C.tape_used
InheritComponent needs to be set up like this.

```suggestion
/datum/component/taped/InheritComponent(datum/component/taped/C, i_am_original, obj/item/stack/tape/tape_used)
	var/obj/I = parent
	if(C)
		src.tape_used = C.tape_used
	else
		src.tape_used = tape_used
```

2020-10-14 01:33 UTC, AsciiSquid commented on waspstation/code/datums/components/taped.dm
> +	src.tape_used = C.tape_used
Applied the fix and tested, appears to be working.

2020-10-14 08:51 UTC, Superyodeler requested changes
Pretty sure I've figured out why the tape keeps vanishing from the taped up machines for me but not for you. If the tape roll used on the machines gets used all the way up, it gets deleted, and after some random amount of time, the taped component's tape_used value becomes null.

In addition, there is a runtime when using tape on a wall because it tries to fix the wall but the wall doesn't have an integrity.

It is also possible to attempt to use tape to repair your mood by clicking on the hud icon.

2020-10-14 08:51 UTC, Superyodeler commented on waspstation/code/datums/components/taped.dm
> +	var/obj/item/stack/tape/tape_used
This is linking to the actual roll of tape being used. When the roll of tape gets used up completely, it gets deleted, and after some amount of time, this becomes null. I'm guessing the reason it takes a few minutes to vanish is due to some garbage collector stuff, but I'm not positive.

2020-10-14 08:52 UTC, Superyodeler commented on waspstation/code/datums/components/taped.dm
> +	var/obj/item/stack/tape/tape_used
I've seen it take anywhere from less than a minute to around ten to become null after the tape gets finished off.

2020-10-20 02:19 UTC, ATH1909 commented on waspstation/code/game/objects/items/stacks/tape.dm
> +	var/self_delay = 30 //! Also used for the tapecuff delay
wait, what's the normal cuff application delay? on /tg/, it's 3 seconds- is it different on bee? if so, you have false advertising in the OP of this PR.

2020-10-20 02:28 UTC, AsciiSquid commented on waspstation/code/game/objects/items/stacks/tape.dm
> +	var/self_delay = 30 //! Also used for the tapecuff delay
We're a fork of /tg/, don't know why you're bringing up Bee.

You're right about the false advertising though, I tweaked the application to be equal to handcuffs and reduced breakout to 15 seconds. I'll add the changes to the OP.

2020-10-20 03:33 UTC, AsciiSquid commented on waspstation/code/datums/components/taped.dm
> +	var/obj/item/stack/tape/tape_used
Found a workaround by caching the variables actually used instead of storing the whole datum. Should be fixed in the upcoming commit.

2020-10-20 19:12 UTC, Superyodeler requested changes
The tape object being deleted doesn't cause problems anymore, but attempting to repair a wall still causes a runtime. In addition, I discovered that you can use duct tape on an object from any range, not just right next to it.

2020-10-20 20:56 UTC, AsciiSquid commented
Finally found the issue with the walls, apparently I fudged the type sanitization **and** forgot to check proximity flags. After banging my head on the desk for a few hours I added the corrections. Gameplay-wise an intent requirement was added to prevent overlap of the embed tape application and repairing tape application.

To apply the embed to items use **disarm intent**, to repair *any* obj use **help intent** and hopefully no more bugs ever again.

2020-10-20 21:47 UTC, Superyodeler requested changes
One more issue: autolathes currently cannot be repaired with tape with this change, they just spit out the message, "The professional-grade duct tape does not contain sufficient materials to be accepted by the autolathe."
The protolathes also send this message, but they get repaired anyways.

2020-10-20 23:10 UTC, AsciiSquid commented
that seems to be more a bug with the lathes than the tape, not really a graceful way to bypass the material component calls

2020-10-21 00:29 UTC, Superyodeler requested changes
Found a item_flag that prevents the autolathe from trying to eat the tape, allowing it to actually get applied.

2020-10-21 00:29 UTC, Superyodeler commented on waspstation/code/game/objects/items/stacks/tape.dm
> +	item_flags = NOBLUDGEON
```suggestion
	item_flags = NOBLUDGEON | NO_MAT_REDEMPTION
```

2020-10-21 00:34 UTC, Superyodeler commented
It looks like the reason this works is it gets the Autolathe's Material_Container's OnAttackBy proc to return before it can cancel the afterattack.

2020-10-21 00:45 UTC, AsciiSquid commented on waspstation/code/game/objects/items/stacks/tape.dm
> +	item_flags = NOBLUDGEON
excuse me while I make the dent in my desk a centimeter deeper

2020-10-21 01:08 UTC, Superyodeler approved these changes
I think it works now.

2020-10-29 00:07 UTC, Superyodeler commented
This has passed the vote and been approved, just needs a merge now.

2020-10-29 00:13 UTC, merged