Finally, a use for Peas.
WaspStation/WaspStation-1.0 pull request #494
Opened 2020-10-01 07:25 UTC by TheObserver-sys

## About The Pull Request
Salad of Eden - Requires a World Pea Cluster, and one sprig of each Ambrosia mutation. Grants Earthsblood, Omnizine, and Happiness as well as nutriment. High effort, high reward.

Fish Fry - Requires carp fillet, peas, and corn. Generally loved by everyone.

Gumbo - Requires boiled rice, peas, a chili pepper, and a cutlet of meat. Grants capsaicin.

Pea Soup - Requires water, 2 peas, a parsnip, and a carrot. Grants occuline in small measure.

Sweet Pea Donut/Jelly Donut - Requires you to juice a Laughin' Pea to produce Laughin' Syrup. Donuts give a slight amount of laughter.

Big ups to Stewydeadmike for the wonderful work on sprites!
It's about time I actually got this shit over here, innit? _More to come. Stay tuned._

## Why It's Good For The Game
More choice is good. Also, having actual foodstuffs attached to your plants gives them more reason to exist outside specific chem traits or medicines, eh?

## Changelog
:cl: The0bserver and Stewydeadmike
add: Hey, there's a bit of dust in this recipe book! Recipes using peas? How many recipes does this book even have?
add: Adds 6 new food items, and 1 new consumable reagent using all forms of the recently discovered peas. Ask your local botanist and chef for them today!
/:cl:

2020-10-01 08:16 UTC, ADepressedPyroshark commented
When are we getting the pea shooter

2020-10-01 08:32 UTC, TheObserver-sys commented
I'm working on the base version, which acts as a stamina damage pistol, expect to see that sooner than not, hopefuly.

2020-10-01 08:34 UTC, ADepressedPyroshark commented
> 
> 
> I'm working on the base version, which acts as a stamina damage pistol, expect to see that sooner than not, hopefully.

Coggers

2020-10-01 14:30 UTC, triplezeta approved these changes
Everything seems solid and the sprites are up to my standards

good shit 10/10

2020-10-02 03:36 UTC, Maldaris requested changes
Looks like most of this code needs to be moved into the `waspstation/` folder, otherwise this looks fine.

2020-10-02 03:36 UTC, Maldaris commented on code/modules/food_and_drinks/food/snacks_meat.dm
> +/obj/item/reagent_containers/food/snacks/fishfry
New code should exist in the `waspstation/` modularization folder if at all possible. It looks like that's the case here. You can create the folder structure/file using the same path here.

2020-10-11 02:10 UTC, Maldaris requested changes
Single modularization comment, otherwise this looks great.

2020-10-11 02:10 UTC, Maldaris commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
Needs a modularization comment

2020-10-11 02:11 UTC, Superyodeler commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
Could possibly be removed, since it's adding 0 of that reagent.

2020-10-11 02:13 UTC, Superyodeler commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
Modularization comment would look like:
`// Waspstation edit - Pea recipies`

2020-10-11 06:47 UTC, triplezeta commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
weirdly enough I think that's how juice_results is supposed to be 
![image](https://user-images.githubusercontent.com/51932018/95672117-4acfe480-0b5b-11eb-8a82-2a3920f350c0.png)

2020-10-11 08:00 UTC, Superyodeler commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
I hate to say it, but I've seen crazier.
Just needs this in that case:
```suggestion
	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)		// Waspstation edit - Pea recipes
```

2020-10-11 08:04 UTC, triplezeta commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
![image](https://user-images.githubusercontent.com/51932018/95673480-1150a680-0b66-11eb-8c01-739c5f47954d.png)
 bruh??

2020-10-11 08:06 UTC, Superyodeler commented on code/modules/hydroponics/grown/peas.dm
> +	juice_results = list(/datum/reagent/consumable/laughsyrup = 0)
Whoops, didn't see that

2020-10-11 08:26 UTC, Maldaris approved these changes

2020-10-12 03:49 UTC, merged