add colt 1911 ammo design disk to cargo ruin
WaspStation/WaspStation-1.0 pull request #514
Opened 2020-10-10 00:58 UTC by Maldaris

## About The Pull Request

## Why It's Good For The Game

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2020-10-10 01:13 UTC, ADepressedPyroshark commented
Ignoring the funny empty pr, is there anything letting the player know that Miss Tiggles drops it? Maybe a "In their dying breath, Miss Tiggles Vomits up a Design Disk!" kinda of thing? It would be better than it just popping out with no context. Also i'm somewhat afraid it will hide under the corpse or something.

2020-10-10 01:18 UTC, Maldaris commented
Note to self: Don't PR while you're half asleep.

To your point Pyro, I'd like to see the existing behavior first. The property I extended to drop the disk is core to the `simple_animal` code.

2020-10-18 04:43 UTC, Superyodeler requested changes
Adding the design to the autolathe currently runtimes and doesn't work.

2020-10-18 04:43 UTC, Superyodeler commented on waspstation/code/modules/projectiles/boxes_magazines/pistol.dm
> +	category = list("Security")
All other design disks add designs to the Imported catagory.
```suggestion
	category = list("Imported")
```

2020-10-18 04:43 UTC, Superyodeler commented on waspstation/code/modules/projectiles/boxes_magazines/pistol.dm
> +	blueprints[1] = ammo_design
Changed to the method used by other disks.
```suggestion
/obj/item/disk/design_disk/ammo_1911
	name = "Design Disk - 1911 Magazine"
	desc = "A design disk containing the pattern for the classic 1911's seven round .45ACP magazine."

/obj/item/disk/design_disk/ammo_1911/Initialize()
	. = ..()
	var/datum/design/colt_1911_magazine/M = new
	blueprints[1] = M
```

2020-11-01 05:12 UTC, MarkSuckerberg commented on waspstation/code/modules/projectiles/boxes_magazines/pistol.dm
> +	var/datum/design/colt_1911_magazine/M = new
```suggestion
	var/datum/design/ammo/colt_1911_magazine/M = new
```

2020-11-06 00:16 UTC, Maldaris commented
@Superyodeler if you can sign off on this that'd be great.

2020-11-06 01:23 UTC, Superyodeler commented
I will check this out again today or tomorrow.

2020-11-06 16:57 UTC, Superyodeler approved these changes

2020-11-06 22:46 UTC, Maldaris commented
Passed vote, merging.

2020-11-06 22:46 UTC, merged