puts bullets in the security techfab (they aren't free)
WaspStation/WaspStation-1.0 pull request #521
Opened 2020-10-16 06:06 UTC by dinnerwoerror

## About The Pull Request

i think it's stupid that you cant get dinky little handgun cartridges without spending big bucks on a super illegal emag type thing, so why should a man not just shoot up the security department and use their techfab to make more ammunition for themselves?
## Why It's Good For The Game

you can now get your hands on a security techfab to make more ammunition (note, there are only 2 that are in existence on the station, and it's really hard to find another one off the station)

## Changelog
:cl:
add: the security techfab has the functionality of making a handful of very common handgun calibers, although it's still wedged inside ballistic technology, so fat chance of you ever actually building any
/:cl:

2020-10-16 06:08 UTC, Maldaris commented on code/modules/research/designs/weapon_designs.dm
> +/datum/design/c10mm //WS edit - sideline lethals
I like most of this, but my one gripe is we're including Stetchkin-caliber ammo in the lathe. Unless I'm mistaken most of the ammo in the tator arsenal is 10mm? Are there any examples of guns that aren't?

2020-10-16 06:09 UTC, dinnerwoerror commented on code/modules/research/designs/weapon_designs.dm
> +/datum/design/c10mm //WS edit - sideline lethals
the surplus rifle
the projectile pistol
that's literally about it

2020-10-16 06:10 UTC, Maldaris commented on code/modules/research/designs/weapon_designs.dm
> +/datum/design/c10mm //WS edit - sideline lethals
Surplus rifle is Jake from State Farm's primary, and the pistol is again, a syndicate item. I'd recommend we take this out of the normal techweb and make it part of the emag set (if it's not already).

2020-10-16 06:22 UTC, dinnerwoerror commented on code/modules/research/designs/weapon_designs.dm
> +/datum/design/c10mm //WS edit - sideline lethals
what 10mm ammo? it never existed

2020-10-28 09:04 UTC, Superyodeler requested changes
I'm assuming the 9mm box is meant for the stetchkin, but the stetchkin uses 10mm ammo.

2020-10-28 18:32 UTC, dinnerwoerror commented
ok and what about it

2020-10-28 18:50 UTC, dinnerwoerror commented
if you want the 10 millimeter ammunition say yes or no

2020-10-28 19:06 UTC, Baldir-Odensen commented
The 9mm ammo could be for the APS.

Can't remember if there is a method of getting aps bullets other than lootbox crate possibly

2020-10-28 19:21 UTC, TheNeoGamer42 commented
9mm is for commanders too I think, which it also looks like you didn't keep the commander mag recipe

2020-11-16 06:56 UTC, closed without merging