Actually Finishing the gun cells
WaspStation/WaspStation-1.0 pull request #537
Opened 2020-10-31 15:23 UTC by Baldir-Odensen

## About The Pull Request

In febuary i made the Weapon gun cells. Now i have decided to finish it. the weapon gun cells will now fit in the secbelt and webbing, not fit in the RPED and i moved the cells from the power section to the weapon section to be with all the other magazines.

## Why It's Good For The Game

this was the original intention behind the guncells. you can no longer carry 100 guncells in a bluespace RPED but they instead fit in the secbelt. this will make them more useable by security and posibly more user friendly.

## Changelog
:cl:
del: Removed the RPED is now unable to accept weapon cells.
tweak: The secbelt has been modified to take weapon cells,
tweak: the gun cell design has been moved from power to weapons.
/:cl:

2020-11-01 04:58 UTC, MarkSuckerberg requested changes

2020-11-01 04:58 UTC, MarkSuckerberg commented on code/game/objects/items/storage/belt.dm
> +		/obj/item/stock_parts/cell/gun   //waspstation eddit Gun cells fit where they should and not where they dont
```suggestion
		/obj/item/stock_parts/cell/gun   //Waspstation edit Gun cells fit where they should and not where they dont
```
nitpick

2020-11-01 04:58 UTC, MarkSuckerberg commented on code/modules/research/designs/weapon_designs.dm
> +
```suggestion

//Wasp Edit - Energy Gun power cells
```

2020-11-01 04:58 UTC, MarkSuckerberg commented on code/modules/research/designs/weapon_designs.dm
> +	departmental_flags = DEPARTMENTAL_FLAG_SCIENCE | DEPARTMENTAL_FLAG_SECURITY
```suggestion
	departmental_flags = DEPARTMENTAL_FLAG_SCIENCE | DEPARTMENTAL_FLAG_SECURITY
//Wasp end
```

2020-11-01 12:00 UTC, Baldir-Odensen commented
ok i think i have done the things now

2020-11-02 00:16 UTC, MarkSuckerberg approved these changes
👍

2020-11-04 00:06 UTC, Maldaris commented
This is a fix for an existing feature, this shouldn't require a vote.

2020-11-12 01:30 UTC, merged