lieutenant envirosuit and skirt and lieutenant+brigphys hud icons too
WaspStation/WaspStation-1.0 pull request #542
Opened 2020-11-03 06:46 UTC by dinnerwoerror

## About The Pull Request

exactly what you think it is

i think they look a little nice

![Screenshot (955)](https://user-images.githubusercontent.com/58999300/97956259-0cde6e80-1d5d-11eb-95f2-bb5b1ebd7c49.png)

**P**

and yes, lieutenant plasma does spawn with combat gloves, because the normal lieutenant gets them

## Why It's Good For The Game

i want to play lieutenant too

## Changelog
:cl:
add: lieutenant envirosuit & skirt
add: lieutenant & brigphys hud icons

2020-11-03 06:54 UTC, triplezeta commented
nice

**P**

2020-11-03 07:05 UTC, dinnerwoerror commented
the lieutenant's hud icon might look a little familiar to some

the psychologist's hud icon is also just **P** as well, but with the cyan blue medical department background color

i think there are already a lot of white cross medical staff hud icons, i think the fourth time is the charm here with the medical doctor and paramedic and cmo and medical response officer all having the same white cross but with different background colors

yes, the depiction of the **red** cross icon here is technically a violation of the geneva conventions, but that's beside the point

2020-11-03 07:06 UTC, triplezeta commented
difference with the psychologist is that there is already a cyan blue background white cross icon (the medical doctor) while security red background white cross icon is a niche not yet filled

2020-11-03 20:21 UTC, triplezeta approved these changes
works for me

2020-11-03 21:32 UTC, Superyodeler requested changes
Really? Again?

2020-11-03 21:33 UTC, Superyodeler commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
Really?

2020-11-03 21:33 UTC, triplezeta commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
the lieutenant gets combat gloves you moth

2020-11-03 21:33 UTC, Superyodeler commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
Shoot, didn't read

2020-11-03 21:35 UTC, triplezeta commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
![image](https://user-images.githubusercontent.com/51932018/98043014-c8e17d00-1de1-11eb-9a27-17be6e8ffffc.png)

2020-11-03 21:44 UTC, Superyodeler requested changes
Actual, semi-intelligent change request.

2020-11-03 21:44 UTC, Superyodeler commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
am dumb

2020-11-03 21:44 UTC, Superyodeler commented on code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
> +/obj/item/clothing/under/plasmaman/lieutenant/skirt
Margularize
```suggestion
/obj/item/clothing/under/plasmaman/lieutenant/skirt //WS edit plasmaman customization
```

2020-11-03 21:44 UTC, Superyodeler commented on code/modules/clothing/under/jobs/Plasmaman/civilian_service.dm
> +/obj/item/clothing/under/plasmaman/lieutenant
Margularize
```suggestion
/obj/item/clothing/under/plasmaman/lieutenant //WS edit plasmaman customization
```

2020-11-03 21:44 UTC, Superyodeler commented on code/modules/clothing/spacesuits/plasmamen.dm
> +/obj/item/clothing/head/helmet/space/plasmaman/security/lieutenant
Margularize
```suggestion
/obj/item/clothing/head/helmet/space/plasmaman/security/lieutenant //WS edit plasmaman customization
```

2020-11-03 21:44 UTC, Superyodeler commented on code/modules/clothing/outfits/plasmaman.dm
> +/datum/outfit/plasmaman/lieutenant
Margularize
```suggestion
/datum/outfit/plasmaman/lieutenant //WS edit plasmaman customization
```

2020-11-03 21:51 UTC, Superyodeler commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
Am dumb

2020-11-03 21:56 UTC, dinnerwoerror commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
right there, in case you missed it

![Screenshot (956)](https://user-images.githubusercontent.com/58999300/98044825-5621d300-1ddc-11eb-9a19-8615096553e9.png)

2020-11-03 22:22 UTC, Superyodeler requested changes
An entry also needs to be added to this switch statement for the outfit to appear ingame: https://github.com/WaspStation/WaspStation-1.0/blob/d8b3dcb31b4a8f9b06bb7092337a8e499e5ad71d/code/modules/mob/living/carbon/human/species_types/plasmamen.dm#L72

2020-11-03 22:29 UTC, Superyodeler commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
:moffdonk:

2020-11-03 23:32 UTC, dinnerwoerror commented
there we go

2020-11-03 23:37 UTC, Superyodeler requested changes
Margularize

2020-11-03 23:37 UTC, Superyodeler commented on code/modules/mob/living/carbon/human/species_types/plasmamen.dm
> +			O = new /datum/outfit/plasmaman/lieutenant
arg
```suggestion
		if("Lieutenant")	//WS edit plasmaman customization
			O = new /datum/outfit/plasmaman/lieutenant	//WS edit plasmaman customization
```

2020-11-04 18:30 UTC, dinnerwoerror commented on code/modules/clothing/outfits/plasmaman.dm
> +	gloves = /obj/item/clothing/gloves/combat
it still boggles me how the lieutenant has to be the odd one out

2020-11-05 05:29 UTC, Superyodeler approved these changes
Works fine

2020-11-14 20:54 UTC, merged