Restore lost squid icons
WaspStation/WaspStation-1.0 pull request #547
Opened 2020-11-11 05:35 UTC by AsciiSquid

## About The Pull Request
Restores a number of icons that were missing for squids, including:
**Ability icons**
![image](https://user-images.githubusercontent.com/39249137/98772437-49891600-23ac-11eb-9bc8-b6c08f60456c.png)
**Tongue organ and squid meat from butchering**
![image](https://user-images.githubusercontent.com/39249137/98772485-63c2f400-23ac-11eb-87ce-926a39fdcf29.png)
As well as the black outline which is now applied to anyone who slips in squid ink. That isn't a missing feature, I just asked Zeta to do these sprites _months_ ago (_with payment_) and he never got back to me on it.
![image](https://user-images.githubusercontent.com/39249137/98772572-a4227200-23ac-11eb-9e5a-a531dab0ee95.png)
Also the speech icon for Rylethian, the squid language.

## Why It's Good For The Game
Missing icons bad. Repent moth spriter.

## Changelog
:cl:
imageadd: adds icons related to squids that were previously missing
tweak: squid ink now outlines it's victims
/:cl:

2020-11-11 07:27 UTC, dinnerwoerror commented
ink

2020-11-14 21:15 UTC, MarkSuckerberg requested changes
Only thing needed from the looks of it

2020-11-14 21:15 UTC, MarkSuckerberg commented on waspstation/code/game/objects/effects/decals/cleanable/misc.dm
> +	M.visible_message("<span class='warning'>[M.name] gets covered in squid ink, leaving a hedious outline around them!</span>", "<span class='warning'>You get squid ink all over yourself, it's horrible
```suggestion
	M.visible_message("<span class='warning'>[M.name] gets covered in squid ink, leaving a hideous outline around them!</span>", "<span class='warning'>You get squid ink all over yourself, it's horrible!</span>")
```

2020-11-19 06:40 UTC, Maldaris approved these changes

2020-11-19 06:40 UTC, merged