Wack BSM mining rate with the nerf bat.
WaspStation/WaspStation-1.0 pull request #562
Opened 2020-11-16 01:56 UTC by Maldaris

## About The Pull Request

Reduces BSM Mining rate to the following values based on laser rating:
```
Tier 1: 10 ^ 1
Tier 2: 10 ^ sqrt(2)
Tier 3: 10 ^ sqrt(3)
Tier 4: 10 ^ 2
```
Also adjusts the parts required for BSM construction as follows:
```
Matter Bin: 3 -> 10
Micro Laser: 1 -> 5
Manipulator: 3 -> 10
Scanning Module: 1-> 3
Bluespace Crystal 3 -> 5
```

## Why It's Good For The Game

Makes the curve of BSM material production less aggressively high to offset the way mining chance scales with manipulators.

Couple this with the increase in parts requirements and it should make it harder to hit the material production levels seen with current T4 BSMs (3x T4s will make all the material a station will ever need right now)

I don't really want to do this but it's really just more numerical nerfbats until #320 is finished (👀 @AsciiSquid )

## Changelog
:cl:
balance:  Adjust BSM material generation rates
balance:  Increase parts requirements for BSMs
/:cl:

2020-11-16 03:41 UTC, Superyodeler requested changes
An issue with this that I can see is that all the changes except for the micro laser change the number of parts without changing the logic that uses them. For example, I'm pretty sure to get tier4 ores the BSM would only need one top tier scanning module, the rest could be bottom tier.

Addition - Looks like the Micro lasers wouldn't work well with multiple parts either

2020-11-16 03:49 UTC, AsciiSquid commented
@Superyodeler Makes a good point, increasing the the part count on the originally single parts means the upgrade effect is going to become unpredictable as it will be set to whatever part is found on the last for-loop iteration.

Additionally, adding extra scaled parts will dramatically affect the scaling limits.

For example, the adjusted part-count for manipulators makes the *minimum* proc chance calculation 200, which somewhat defeats the point.

2020-11-16 04:01 UTC, Maldaris commented
Made changes per review, dropped the vast majority of part increases because aforementioned maffs.

2020-11-16 06:33 UTC, dinnerwoerror commented
when i tried to get into NSV, for like 5 or so rounds, there was always that one scientist who made like 90 fully upgraded bluespace miners regardless of whether or not there were any miners or cargo staff

2020-11-16 15:45 UTC, AsciiSquid commented on code/modules/mining/machine_bluespaceminer.dm
> +		mining_rate = 10 ** (ML.rating > 3 ? ML.rating - 2 : sqrt(ML.rating))
```suggestion
		mining_rate = 10 ** (ML.rating > 1 ? sqrt(ML.rating) : ML.rating)
```
Sqrt(4) = 2; quik mafs. Somewhat nitpicky but I feel this setup is more readable

2020-11-16 15:47 UTC, Maldaris commented on code/modules/mining/machine_bluespaceminer.dm
> +		mining_rate = 10 ** (ML.rating > 3 ? ML.rating - 2 : sqrt(ML.rating))
Was supposed to be a tiny optimization but I guess it doesn't really matter.

2020-11-17 01:25 UTC, Superyodeler approved these changes

2020-11-19 19:00 UTC, merged