Brings back the naughty words
WaspStation/WaspStation-1.0 pull request #569
Opened 2020-11-18 16:06 UTC by Jack7D1

DRAFT NOTE: this PR will take some time as its very important this this process NOT slow down bootup by 10 seconds and also will ensure that the created code does not create any spaghetti.
## About The Pull Request
Will bring back the naughty words while maintaining their nonpresence on the repo and on other servers in a fast way

## Why It's Good For The Game
no data

## Changelog
:cl:
code: Naughty words are back
/:cl:

2020-11-18 16:25 UTC, Superyodeler commented
Do not spook wonerfil raptil

2020-11-18 16:41 UTC, Maldaris commented
Would like to go on record as having said: this PR is unnecessary for its stated/implied use on our server. We are an 18+ server and community, which does abide by the freedom of speech.

That being said I do think this has some fun potential for encrypting strings for exploration content. This could be used to mildly obfuscate puzzles and content that would otherwise be readable/complete-able in singleplayer. Very interested to see where this goes.

2020-11-18 17:20 UTC, Shadowtail117 requested changes

2020-11-18 17:20 UTC, Shadowtail117 commented on code/game/world.dm
> +/var/global/list/badwordlist[BAD_WORD_COUNT]
The game doesn't like when you declare global stuff like this. Use `GLOBAL_LIST_INIT`.

2020-11-18 17:29 UTC, Jack7D1 commented on code/game/world.dm
> +/var/global/list/badwordlist[BAD_WORD_COUNT]
good idea!

2020-11-18 23:56 UTC, Shadowtail117 commented on code/__DEFINES/misc.dm
> +End bad words*/
So will we have to define `BAD_WORD_2_VAL BAD_WORD_2_HASH BAD_WORD_2_TARGET` `BAD_WORD_3_VAL _BAD_WORD3_HASH BARD_WORD_3_TARGET` here whenever we want to add new elements to the list?

Seems better to either make it a config thing or use global lists that are a bit more mutable than new defines for each entry.

2020-11-19 00:01 UTC, Jack7D1 commented on code/__DEFINES/misc.dm
> +End bad words*/
Do you think three separate global lists corresponding to the same thing would be better? To me preprocessors seems a lit less heavy than adding new vars but if it'll be more convenient/clean then ye

2020-11-19 00:03 UTC, Shadowtail117 commented on code/__DEFINES/misc.dm
> +End bad words*/
Bear in mind that these entries are defined *everywhere*. And I don't imagine there would be literally thousands of entries where performance would take a measurable hit.

Global lists are cleaner and generally easier to use than having to deal with many, many defines which you'd have to input manually into two places.

2020-11-19 16:36 UTC, Jack7D1 commented on code/__DEFINES/misc.dm
> +End bad words*/
Implemented a subsystem specific 2d array!

2020-11-20 01:52 UTC, tiramisuapimancer commented
this is a lot of work to be able to make meatballs called a slur again

2020-11-20 02:24 UTC, Maldaris commented
> this is a lot of work to be able to make meatballs called a slur again

See this snippet from my comment above.

> That being said I do think this has some fun potential for encrypting strings for exploration content. This could be used to mildly obfuscate puzzles and content that would otherwise be readable/complete-able in singleplayer. Very interested to see where this goes.

2020-11-20 02:48 UTC, tiramisuapimancer commented
yeah i read it i just feel off about the initial intent

2020-11-20 03:56 UTC, Jack7D1 commented
the power of autism is with me

2020-11-20 03:58 UTC, Jack7D1 commented
no slurs on this codebase at all

2020-11-20 04:05 UTC, AsciiSquid commented
The initial intent is to test this tech on something simple and unobtrusive. Renaming a meatball to something we know can't be in the code anywhere is a start.

Shame people made the word for British meatballs naughty, however it's reintroduction shouldn't be something to take too seriously. It's all in good fun.

2020-11-20 04:29 UTC, dee-dubya commented
<img src="https://cdn.discordapp.com/attachments/221734126070267906/779201627314978866/866005e39dc4b2ec27d941d1ba7b1a2ce3ca3ff07e02aace1c90919d8122e169_1.png">

2020-11-20 04:30 UTC, dee-dubya commented
the only thing that worries me about this rabbit hole is the potential of possibly obfuscating code from the maintainers themselves, sneaking in changes or features that we wouldn't want

2020-11-20 04:34 UTC, Sparrowbird611 commented
time to sneak ERP verbs into a PR :)

2020-11-20 04:36 UTC, AsciiSquid commented
sadly this seems to only do strings, at best we can use this to obscure switch statements

and no ERP is still enforced. I **WILL** ban the code if I have to.

2020-11-20 10:34 UTC, Jack7D1 commented
This serves the use of obscuring certain recipes and other hints that may appear in game. Along with any general phrases that should not be able to be ctrl+f'able in our repo.

2020-11-20 20:27 UTC, Jack7D1 commented
warranty void if used for erp

2020-11-25 21:43 UTC, MarkSuckerberg approved these changes
Looks good :+1:

2020-12-03 23:56 UTC, merged