the botany chem fixes+
WaspStation/WaspStation-1.0 pull request #584
Opened 2020-11-24 09:09 UTC by Baldir-Odensen

well posibly should atmoize this

## About The Pull Request
some plants produces non existant chemicals. also adds sodium to ghost chilli because zeta said it would fit in it.

## Why It's Good For The Game
well plants should produce stuff. and sodium production is funni

## Changelog
:cl:
tweak: added sodium to ghost chilli
fix: made it so toxin healing plants produce toxin healing.
/:cl:

2020-11-24 16:12 UTC, triplezeta requested changes

2020-11-24 16:12 UTC, triplezeta commented on code/modules/hydroponics/grown/kudzu.dm
> +	reagents_add = list(/datum/reagent/medicine/antitoxin = 0.04, /datum/reagent/consumable/nutriment = 0.02)
make this charcoal instead, as that is what multiver was originally

2020-11-24 16:12 UTC, triplezeta commented on code/modules/hydroponics/grown/mushrooms.dm
> +	reagents_add = list(/datum/reagent/medicine/morphine = 0.35, /datum/reagent/medicine/antitoxin = 0.35, /datum/reagent/consumable/nutriment = 0)
this too

2020-11-24 17:51 UTC, Baldir-Odensen commented on code/modules/hydroponics/grown/kudzu.dm
> +	reagents_add = list(/datum/reagent/medicine/antitoxin = 0.04, /datum/reagent/consumable/nutriment = 0.02)
Having charcoal as a natural product of a plant growing doesn't make much sense to me. Nor is it intuitive.

2020-11-25 17:21 UTC, triplezeta approved these changes
cool

2020-11-29 00:01 UTC, MarkSuckerberg approved these changes

2020-11-29 00:59 UTC, Superyodeler approved these changes

2020-11-30 17:05 UTC, merged