re:tools
WaspStation/WaspStation-1.0 pull request #602
Opened 2020-11-29 09:22 UTC by triplezeta

## About The Pull Request

this resprites some tool sprites. again.

Azlan's (AzlanonPC, Azlan#0852, someangryminer, etc.)  screwdriver sprite has been taken and modified to replace our current one.
![image](https://user-images.githubusercontent.com/51932018/100537864-40d87280-31e9-11eb-8bf0-92dce58b8b08.png)

multitool and geiger counter have been given fresh, vibrant palettes instead of the dull desaturated ones from before.
![image](https://user-images.githubusercontent.com/51932018/100537835-08389900-31e9-11eb-8de7-13ac9415898a.png)

a lot of unique inhands have been added for things that really should've gotten unique inhands, such as the pipe wrench and the syndicate tool variants (except for the screwdriver and wirecutters   and also welder tools), along with the geiger and jaws of life inhands being fixed.
![image](https://user-images.githubusercontent.com/51932018/100537872-4b930780-31e9-11eb-8a3b-873659ca5552.png)

T-ray scanner looks a bit different.
![image](https://user-images.githubusercontent.com/51932018/100537800-cf002900-31e8-11eb-9e2c-09d0646715c8.png)

Analyzer has been returned to its original shape, but heavily desouled. 
![image](https://user-images.githubusercontent.com/51932018/100537809-e50de980-31e8-11eb-9328-bf5e96d96f67.png)

## Why It's Good For The Game

soul b gone

## Changelog
:cl:
imageadd: inhands have been fixed for some tools, added and/or desouled for others.
imageadd: Azlan's screwdriver sprite
imageadd: multitool, geiger counter, t-ray scanner, gas analyzer, have all received new sprites
imagedel: my old screwdriver sprites
/:cl:

2020-11-30 22:25 UTC, trerri commented
the right bit on the new analyzer sucks, the reds dont work at all and it looks downright blurry

2020-12-02 21:30 UTC, MarkSuckerberg commented on code/game/objects/items/tools/wrench.dm
> +	icon_state = "wrench_pipe" //now where could my pipe wrench be?
GARFIELD

2020-12-02 21:31 UTC, MarkSuckerberg commented on waspstation/code/game/objects/items/devices/multitool.dm
> +	desc = "Used for pulsing wires to test which to cut. This one looks.. 'retro'. It wasn't recommended by doctors then and won't be recommended by doctors now."
```suggestion
	desc = "Used for pulsing wires to test which to cut. This one looks... 'retro'. It wasn't recommended by doctors then and won't be recommended by doctors now."
```

2020-12-02 22:22 UTC, Superyodeler requested changes
Sprites look good, but the syndie multitool is using the regular multitool's inhand sprites.

2020-12-02 22:22 UTC, Superyodeler commented on waspstation/code/game/objects/items/devices/multitool.dm
>  	toolspeed = 0.5
Looks like it's just using the default multitool's inhands.

2020-12-02 22:39 UTC, triplezeta commented on waspstation/code/game/objects/items/devices/multitool.dm
>  	toolspeed = 0.5
fuck

2020-12-04 22:58 UTC, Superyodeler approved these changes

2020-12-07 14:04 UTC, merged