Adds Cuban Pete's Classic Beats
WaspStation/WaspStation-1.0 pull request #608
Opened 2020-12-02 02:49 UTC by LastCrusader105

## About The Pull Request
credit to Kryyto for the sprite
Adds Cuban Pete's Classic Beats a instrument vending machine

## Why It's Good For The Game
now you can play tunes whenever you want

## Changelog
:cl:
add: Added new vending machine and new sprites for it
/:cl:

2020-12-02 02:51 UTC, LastCrusader105 commented
packed (agreed by anime tiddie)
![image](https://user-images.githubusercontent.com/56616002/100821785-f81ef480-3448-11eb-96ac-fd66cc588c4e.png)
midway (no idea who made the map)
![image](https://user-images.githubusercontent.com/56616002/100821834-1553c300-3449-11eb-9fd3-33a07e1f2512.png)
box
![image](https://user-images.githubusercontent.com/56616002/100821854-1d136780-3449-11eb-86a3-245faedf1b39.png)
delta
![image](https://user-images.githubusercontent.com/56616002/100821864-26043900-3449-11eb-89a5-c25f73753cf0.png)
kilo
![image](https://user-images.githubusercontent.com/56616002/100821878-2bfa1a00-3449-11eb-96a1-8828710c4956.png)
meta
![image](https://user-images.githubusercontent.com/56616002/100821896-32889180-3449-11eb-9d74-b3a9af7bbdb6.png)
and pubby
![image](https://user-images.githubusercontent.com/56616002/100821916-3a483600-3449-11eb-9d10-10e5491baf33.png)

2020-12-02 21:34 UTC, MarkSuckerberg requested changes

2020-12-02 21:34 UTC, MarkSuckerberg commented on code/modules/vending/classicbeats.dm
> +	product_ads = "Chick-Chicky Boom,Chick-Chicky Boom!;Take a lesson from Cuban Pete!;Its very nice,So full of spice!;Singin a song,All the day long!"
```suggestion
	product_ads = "Chick-Chicky Boom, Chick-Chicky Boom!;Take a lesson from Cuban Pete!;It's very nice, So full of spice!;Singin' a song, All the day long!"
```

2020-12-05 22:16 UTC, MarkSuckerberg approved these changes

2020-12-09 02:07 UTC, merged