Ports Apids from Beestation!
WaspStation/WaspStation-1.0 pull request #613
Opened 2020-12-05 00:29 UTC by Jack7D1

## About The Pull Request
Ports Apids from Beestation to boomerstation codebase.
See BeeStation/BeeStation-Hornet/pull/2315 and BeeStation/BeeStation-Hornet/pull/1571

This will add a new bee race! They have increased sight, are friendly to bees and have a new special drink the bartender can make!

## Why It's Good For The Game
BEEEEES :b:

## Changelog
:cl:
add: Added new Apids from Beestation!
config: Apids are default to enabled.
/:cl:

2020-12-05 00:34 UTC, hirohito1 commented
merge now merge now merge now merge now merge now

2020-12-05 00:34 UTC, Jack7D1 commented
Not fully tested yet!

2020-12-05 00:36 UTC, triplezeta approved these changes
sprites good

idk about the c*de haha!

2020-12-05 00:36 UTC, Maldaris commented
I gotta admit, not thrilled about the prospect of more races, doubly so for another bug.

2020-12-05 00:40 UTC, Maldaris commented on code/modules/language/apidite.dm
> +	speech_verb = "buzzes"
We already have a language that uses this. I would suggest just giving them the buzzwords, and altering the description to indicate Apids invented it.

2020-12-05 00:45 UTC, Jack7D1 commented on code/modules/language/apidite.dm
> +	speech_verb = "buzzes"
Agreed, wanted to just port directly and let you guys pick at it.

2020-12-05 00:48 UTC, Maldaris requested changes
To clarify my earlier point, here's some things that jumped out at me as needing to be addressed.

2020-12-05 00:48 UTC, Maldaris commented on code/modules/mob/living/carbon/human/species_types/apid.dm
> +	mutantlungs = /obj/item/organ/lungs/apid
This effect isn't listed anywhere in the PR description or changelog, please update it to better inform the PR voting process.

2020-12-05 00:48 UTC, Maldaris commented on code/modules/mob/living/carbon/human/species_types/apid.dm
> +	if(istype(weapon, /obj/item/melee/flyswatter))
See previous comment about changelog

2020-12-05 00:48 UTC, Maldaris commented on code/modules/surgery/organs/eyes.dm
> +/obj/item/organ/eyes/apid
This is the second bug race with night vision, this time without downsides via flash vulnerability.

2020-12-05 00:48 UTC, Maldaris commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
See previous changelog comment.

This seems incredibly overpowered with little downside.

2020-12-05 00:48 UTC, Maldaris commented on code/modules/mob/living/carbon/human/species_types/apid.dm
> +	disliked_food = GROSS | DAIRY
One way this race could be balanced would be to heavily restrict their diet. Consider making these toxic instead.

2020-12-05 01:26 UTC, triplezeta commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
incredibly is a strong word

2020-12-05 01:50 UTC, Jack7D1 commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
Perhaps if I made apids more sensitive to miasma equivalent to the percentage decrease of oxygen required?

2020-12-05 01:50 UTC, Jack7D1 commented on code/modules/mob/living/carbon/human/species_types/apid.dm
> +	disliked_food = GROSS | DAIRY
I like this idea!

2020-12-05 01:51 UTC, Jack7D1 commented
Also why is galaxy station causing the checks to fail, I didn't touch it

2020-12-05 01:51 UTC, dee-dubya commented
not enough downsides with the benefits they have

rule of thumb is that all roundstart races should be equal to or inferior to humans(lean towards slightly inferior)

2020-12-05 01:52 UTC, Jack7D1 commented
@dee-dubya What would you think about simply turning moth eyes into insect eyes and using them across apids and moths?

2020-12-05 01:54 UTC, dee-dubya commented
if you did that and implemented the harsher dietary restrictions, I think it'd be back in line with the racial standards

2020-12-05 01:55 UTC, Superyodeler commented
The map test has been weird for a while.

2020-12-05 02:50 UTC, TheNeoGamer42 commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
maybe make them take a shitton more toxin damage from plasma in the air, since their lungs get more of it essentially

2020-12-05 02:50 UTC, TheNeoGamer42 commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
maybe not a SHITTON but just more compared to your average spessmans

2020-12-06 20:58 UTC, Jack7D1 commented on code/modules/surgery/organs/eyes.dm
> +/obj/item/organ/eyes/apid
Planning on merging moth eyes and apid eyes to be slightly better night vision with higher flash vulnerability

2020-12-07 02:27 UTC, Jack7D1 commented
Testing and fixing complete! Ready for mergies when ready!

2020-12-07 05:36 UTC, DerFlammenwerfer commented
Jack, make sure you go into the DME file and include hull.dm in the modular turfs folder.

2020-12-07 13:13 UTC, Jack7D1 commented
@DerFlammenwerfer Oh! That's what's causing galaxy to go all screwy? Thanks!

2020-12-07 13:48 UTC, Maldaris requested changes
If you have any question about the changes below please @ me in discord.

2020-12-07 13:48 UTC, Maldaris commented on waspstation/code/modules/mob/living/carbon/human/species_types/spider.dm
> -/obj/item/organ/eyes/night_vision/spider
I take serious umbrage with this, and the changes to Moths.

Here's the thing. When you add new code, it gets voted on, and new features are always welcome, and historically get grossly voted up. But if you sneak in changes like this, you're playing carrot and stick with the codebase. This is poor form.

This will not be merged until this change to Arachnids and Moths is reverted. If you want to rebalance the bug races to share the same eyes (which in of itself is a questionable change) please do so in a separate PR.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
Yeah don't resolve a comment without addressing the changes kthx.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/surgery/organs/eyes.dm
> +	lighting_alpha = LIGHTING_PLANE_ALPHA_NV_TRAIT - 5	//whoa, buggy
Is there a reason we're not using the nightvision code already existing and doing whatever the hell this is? Arachnids got nerfed with their night vision radius, and this seems to kind of fly in the face of that. Consider referencing night vision from Arachnid eyes.

Alternatively, dropping nightvision from these bugs would make more sense. Bees are highly dependent on color for their vision, and do not operate at night. Night Vision among insects is actually quite rare, and even among spiders, predators that benefit from the ability.

2020-12-07 13:48 UTC, Maldaris commented on waspstation/code/modules/mob/living/carbon/human/species_types/apid.dm
> +	SSvis_overlays._create_new_vis_overlay()
What visual overlay is being created here? Comment with some minor documentation please.

2020-12-07 13:48 UTC, Maldaris commented on code/_globalvars/lists/names.dm
> +GLOBAL_LIST_INIT(apid_names_male, world.file2list("strings/names/apid_first_male.txt"))
Margularization comments please.

2020-12-07 13:48 UTC, Maldaris commented on code/datums/mood_events/drink_events.dm
> +/datum/mood_event/quality_bad
Margularization comments please.

2020-12-07 13:48 UTC, Maldaris commented on code/game/objects/effects/spawners/lootdrop.dm
> +		/obj/item/organ/eyes/compound,
Margularization comment please.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/food_and_drinks/food/snacks/meat.dm
> +/obj/item/reagent_containers/food/snacks/meat/slab/human/mutant/apid
Margularization comments please.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/food_and_drinks/recipes/drinks_recipes.dm
> +/datum/chemical_reaction/beesknees
Margularization comments please.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/hydroponics/beekeeping/beebox.dm
> +	if(HAS_TRAIT(src, TRAIT_BEEFRIEND))
Margularization comments please.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/language/language_holder.dm
> +/datum/language_holder/apid
If you don't reference this in any of the main code segments, consider moving it to the `waspstation/` folder. Same goes for any of the other comments regarding modularization.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/mining/lavaland/necropolis_chests.dm
> +		if(reac_volume < 5 || !(holycheck || isapid(C) || islizard(C) || (ismoth(C) && C.dna.features["moth_wings"] != "Burnt Off"))) // implying xenohumans are holy //as with all things,
Margularization comment please.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/wings/apid
See earlier comment about modularization and the `waspstation/` folder.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/species/apid
See above comment about modularization and the `waspstation/` folder.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/mob/living/carbon/human/species_types/mothmen.dm
> +	mutanteyes = /obj/item/organ/eyes/compound
See previous comment about reverting this change in favor of atomizing the change in another PR.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/mob/living/carbon/human/species_types/podpeople.dm
> -	species_traits = list(MUTCOLORS,EYECOLOR)
Margularization comment please.

2020-12-07 13:48 UTC, Maldaris commented on code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
> +
See previous comments about modularization and the `waspstation/` folder.

2020-12-07 13:52 UTC, Jack7D1 commented on waspstation/code/modules/mob/living/carbon/human/species_types/spider.dm
> -/obj/item/organ/eyes/night_vision/spider
Allright! I'll give them eyes identical to Moth eyes in the interim!

2020-12-07 13:54 UTC, Jack7D1 commented on code/modules/surgery/organs/eyes.dm
> +	lighting_alpha = LIGHTING_PLANE_ALPHA_NV_TRAIT - 5	//whoa, buggy
The night vision code that exists creates a hud button that effectively allows for fullbright mode, see /nightvision/. After some testing I came that the parameters of see_indark and lighting_alpha would be most favorable at those values.

2020-12-07 13:55 UTC, Jack7D1 commented on code/_globalvars/lists/names.dm
> +GLOBAL_LIST_INIT(apid_names_male, world.file2list("strings/names/apid_first_male.txt"))
oh yeah! whoop

2020-12-07 13:55 UTC, Jack7D1 commented on code/modules/mob/dead/new_player/sprite_accessories.dm
> +/datum/sprite_accessory/wings/apid
you got it!

2020-12-07 13:56 UTC, Jack7D1 commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
Oh whoops, what would you like changed?

2020-12-07 13:57 UTC, Maldaris commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
Any kind of vulnerability to balance this out would be adequate, but I would rather it be dropped entirely.

2020-12-07 13:59 UTC, Jack7D1 commented on waspstation/code/modules/mob/living/carbon/human/species_types/apid.dm
> +	SSvis_overlays._create_new_vis_overlay()
oh jeeze, that's nothing code.

2020-12-07 14:00 UTC, Maldaris commented on code/modules/surgery/organs/eyes.dm
> +	lighting_alpha = LIGHTING_PLANE_ALPHA_NV_TRAIT - 5	//whoa, buggy
Right I'm familiar as to how this works, I'd recommend, again, that you take a look at Arachnid eye's method, and how it changed in #379 to balance it out.

2020-12-07 14:06 UTC, Jack7D1 commented on code/modules/surgery/organs/lungs.dm
> +	safe_oxygen_min = 8
Got it!

2020-12-07 14:48 UTC, Jack7D1 commented on code/modules/surgery/organs/eyes.dm
> +	lighting_alpha = LIGHTING_PLANE_ALPHA_NV_TRAIT - 5	//whoa, buggy
ok!

2020-12-07 21:01 UTC, SynnGraffkin commented on waspstation/code/modules/mob/living/carbon/human/species_types/spider.dm
> -/obj/item/organ/eyes/night_vision/spider
I'm agreeing with Mald, and we also kinda have a lot of races now in general with Squids and Arachnids.

2020-12-13 16:31 UTC, Maldaris requested changes
Couple minor modularization concerns. Assuming they can't be extracted into the `waspstation/` folder, just give em comments.

I'm still not thrilled about another bug race though.

2020-12-13 16:31 UTC, Maldaris commented on code/__HELPERS/mobs.dm
> +/proc/random_unique_apid_name(gender, attempts_to_find_unique_name=10)
Margularization comments.

2020-12-13 16:31 UTC, Maldaris commented on code/__HELPERS/names.dm
> +/proc/apid_name(gender)
Margularization comments

2020-12-13 16:31 UTC, Maldaris commented on code/modules/mining/lavaland/necropolis_chests.dm
> +		if(reac_volume < 5 || !(holycheck || isapid(C) /*Waspstation edit - Port Apids*/ || islizard(C) || (ismoth(C) && C.dna.features["moth_wings"] != "Burnt Off")))
Ack, maybe don't inline this, makes it really hard to read. Just put it above.

2020-12-16 18:56 UTC, Tennessee116 commented
[Hi, original coder of Apids here](https://github.com/BeeStation/BeeStation-Hornet/pull/1571),

Apids were a very rushed project and lack actual depth. I'd firmly advise that you try to implement more features for them before porting them.

2020-12-16 19:11 UTC, Maldaris commented
> [Hi, original coder of Apids here](https://github.com/BeeStation/BeeStation-Hornet/pull/1571),
> 
> Apids were a very rushed project and lack actual depth. I'd firmly advise that you try to implement more features for them before porting them.

Thanks for chiming in! We appreciate the feedback. If you have suggestions that you didn't get a chance to implement or work with this is absolutely the venue to present them.

With that being said, I'm going to suggest we mark this PR as a draft, as I completely agree that in their current state Apids aren't feature-rich enough to warrant a port.

2020-12-27 05:12 UTC, closed without merging