Asshat
WaspStation/WaspStation-1.0 pull request #639
Opened 2020-12-14 05:46 UTC by TheNeoGamer42

## About The Pull Request
Adds Asshat as an alternate job title for assistants
## Why It's Good For The Game
why isnt it?
## Changelog
:cl:
add: Asshat is now a job title.
/:cl:

2020-12-14 05:56 UTC, dee-dubya commented
on one hand, this is hilarious

on the other hand, the last thing we want to encourage is assistants acting like asshats. once you get a few of them, they're like a fucking plague that makes the entire server worse off.

2020-12-14 05:57 UTC, TheNeoGamer42 commented
should I just make them start the round on arrest then because fuck you if your going to be an asshat

2020-12-14 05:58 UTC, TheNeoGamer42 commented
actually I dunno how I would do that... hmmmmmmmmmmmm

2020-12-14 06:19 UTC, Maldaris commented
Sounds like a greytider senior title

2020-12-14 16:02 UTC, Shadowtail117 requested changes

2020-12-14 16:02 UTC, Shadowtail117 commented on code/modules/jobs/job_types/assistant.dm
> +	backpack_contents = list(/obj/item/toy/gun=1) //terg said it was a good idea at the time, now asshats can shoot up the station with a cap gun
Requires modularization comment. Comment is unnecessary as well.

2020-12-14 16:04 UTC, Shadowtail117 commented
Failing unit test:
![image](https://user-images.githubusercontent.com/25853190/102104385-fd822480-3de2-11eb-8c24-3c7a2a90b645.png)

2020-12-14 17:28 UTC, Sparrowbird611 commented
Counterpoint:

Why is this a good idea.

2020-12-14 17:32 UTC, Maldaris commented
> Counterpoint:
> 
> Why is this a good idea. It's not even a real job (I know assistant is barely a job, but it at least sounds like something someone would reasonably have, there's no job in existence literally named asshat).

This was kinda why I suggested it be a seniority title. If you've played Assistant long enough to unlock it, chances are you're an asshat and this does the job of drawing attention to that fact.

2020-12-14 17:35 UTC, TheNeoGamer42 commented
Well we already have an assistant senior title thats Greytider, and I dunno if margs funny alt title code can handle more than one senior title without exploding or some shit

2020-12-14 17:36 UTC, Maldaris commented
> Well we already have an assistant senior title thats Greytider, and I dunno if margs funny alt title code can handle more than one senior title without exploding or some shit

Feels like this would be a more apt senior title, but point taken.

2020-12-14 17:37 UTC, Maldaris commented
Also pull master into this branch so the integration tests can pass.

2020-12-14 21:34 UTC, SynnGraffkin commented
I think Assistant titles are fine as is.

2020-12-14 21:35 UTC, triplezeta commented
yes, agreed

2020-12-16 22:11 UTC, MarkSuckerberg commented
Funny, but I don't think it's needed.

2020-12-16 22:11 UTC, closed without merging